sudo: required
language: bash
env:
  global:
 - BASE_IMAGE_NAME=gableroux/unity3d:2019.2.5f1
  - BUILD_NAME=Virush
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_82766e747237_key -iv $encrypted_82766e747237_iv
  -in ./unity3d.alf -out ./Unity_v2019.x.ulf -d
- export UNITY_LICENSE_CONTENT=`cat Unity_v2019.x.ulf`
- rm Unity_v2019.x.ulf
- docker pull $IMAGE_NAME
jobs:
  include:
  - stage: test
    script: "chmod +x ./ci/docker_test.sh && ./ci/docker_test.sh"
    env: TEST_PLATFORM=editmode IMAGE_NAME=gableroux/unity3d:2019.2.5f1
    addons:
      artifacts:
        s3_region: "us-west-1"
        paths:
        - "$(pwd)/$TEST_PLATFORM-results.xml"
  - stage: test
    script: "chmod +x ./ci/docker_test.sh && ./ci/docker_test.sh"
    env: TEST_PLATFORM=playmode IMAGE_NAME=gableroux/unity3d:2019.2.5f1
    addons:
      artifacts:
        s3_region: "us-west-1"
        paths:
        - "$(pwd)/$TEST_PLATFORM-results.xml"
  # - stage: build
  #   env: BUILD_TARGET=StandaloneLinux64 IMAGE_NAME=gableroux/unity3d:2019.2.5f1
  #   script: "chmod +x ./ci/docker_build.sh && ./ci/docker_build.sh"
  #   addons:
  #     artifacts:
  #       s3_region: "us-west-1"
  #       paths:
  #       - "./Builds/"
  # - stage: build
  #   env: BUILD_TARGET=StandaloneOSX IMAGE_NAME=gableroux/unity3d:2019.2.5f1-mac
  #   script: "chmod +x ./ci/docker_build.sh && ./ci/docker_build.sh"
  #   addons:
  #     artifacts:
  #       s3_region: "us-west-1"
  #       paths:
  #       - "./Builds/"
  - stage: build
    env: BUILD_TARGET=StandaloneWindows64 IMAGE_NAME=gableroux/unity3d:2019.2.5f1-windows
    script: "chmod +x ./ci/docker_build.sh &&./ci/docker_build.sh"
    addons:
      artifacts:
        s3_region: "us-west-1"
        paths:
        - "./Builds/"
  - stage: build
    env: BUILD_TARGET=Android IMAGE_NAME=gableroux/unity3d:2019.2.5f1-android
    script: "chmod +x ./ci/docker_build.sh && ./ci/docker_build.sh"
    addons:
      artifacts:
        s3_region: "us-west-1"
        paths:
        - "./Builds/"
